local wezterm = require "wezterm"
local act = wezterm.action

local M = {}

function M.apply_to_config(config)
    config.keys = {
        { key = "Tab", mods = "ALT", action = act.ActivateTabRelative(1) },
        { key = "Tab", mods = "SHIFT|ALT", action = act.ActivateTabRelative(-1) },
        { key = "Enter", mods = "ALT", action = act.ToggleFullScreen },
        { key = "!", mods = "ALT", action = act.ActivateTab(0) },
        { key = "#", mods = "ALT", action = act.ActivateTab(2) },
        { key = ",",  mods = "ALT", action = act.ActivateTab(3) },
        { key = "%", mods = "ALT", action = act.ActivateTab(4) },
        { key = "%", mods = "ALT", action = act.SplitHorizontal{ domain =  "CurrentPaneDomain" } },
        { key = "&", mods = "ALT", action = act.ActivateTab(6) },
        { key = "(", mods = "ALT", action = act.ActivateTab(-1) },
        { key = ")", mods = "ALT", action = act.ResetFontSize },
        { key = "*", mods = "ALT", action = act.ActivateTab(7) },
        { key = "+", mods = "ALT", action = act.IncreaseFontSize },
        { key = "-", mods = "ALT", action = act.DecreaseFontSize },
        { key = "0", mods = "ALT", action = act.ResetFontSize },
        { key = "=", mods = "ALT", action = act.IncreaseFontSize },
        { key = "@", mods = "ALT", action = act.ActivateTab(1) },
        { key = "C", mods = "ALT", action = act.CopyTo "Clipboard" },
        { key = "F", mods = "ALT", action = act.Search "CurrentSelectionOrEmptyString" },
        { key = "K", mods = "ALT", action = act.ClearScrollback "ScrollbackOnly" },
        { key = "L", mods = "ALT", action = act.ShowDebugOverlay },
        { key = "M", mods = "ALT", action = act.Hide },
        { key = "N", mods = "ALT", action = act.SpawnWindow },
        { key = "P", mods = "ALT", action = act.ActivateCommandPalette },
        { key = "R", mods = "ALT", action = act.ReloadConfiguration },
        { key = "T", mods = "ALT", action = act.SpawnTab "CurrentPaneDomain" },
        { key = "U", mods = "ALT", action = act.CharSelect{ copy_on_select = true, copy_to =  "ClipboardAndPrimarySelection" } },
        { key = "V", mods = "ALT", action = act.PasteFrom "Clipboard" },
        { key = "W", mods = "ALT", action = act.CloseCurrentTab{ confirm = true } },
        --! { key = "X", mods = "ALT", action = act.ActivateCopyMode },
        { key = "Z", mods = "ALT", action = act.TogglePaneZoomState },
        { key = "^", mods = "ALT", action = act.ActivateTab(5) },
        { key = "_", mods = "ALT", action = act.DecreaseFontSize },
        { key = "PageUp", mods = "SHIFT", action = act.ScrollByPage(-1) },
        --! { key = "PageUp", mods = "ALT", action = act.ActivateTabRelative(-1) },
        { key = "PageDown", mods = "SHIFT", action = act.ScrollByPage(1) },
        --! { key = "PageDown", mods = "ALT", action = act.ActivateTabRelative(1) },
        --! { key = "LeftArrow", mods = "SHIFT|ALT", action = act.ActivatePaneDirection "Left" },
        -- { key = "LeftArrow", mods = "SHIFT|ALT", action = act.AdjustPaneSize{ "Left", 1 } },
        --! { key = "RightArrow", mods = "SHIFT|ALT", action = act.ActivatePaneDirection "Right" },
        -- { key = "RightArrow", mods = "SHIFT|ALT", action = act.AdjustPaneSize{ "Right", 1 } },
        --! { key = "UpArrow", mods = "SHIFT|ALT", action = act.ActivatePaneDirection "Up" },
        -- { key = "UpArrow", mods = "SHIFT|ALT", action = act.AdjustPaneSize{ "Up", 1 } },
        --! { key = "DownArrow", mods = "SHIFT|ALT", action = act.ActivatePaneDirection "Down" },
        -- { key = "DownArrow", mods = "SHIFT|ALT", action = act.AdjustPaneSize{ "Down", 1 } },
        -- { key = "Insert", mods = "SHIFT", action = act.PasteFrom "PrimarySelection" },
        -- { key = "Insert", mods = "ALT", action = act.CopyTo "PrimarySelection" },
        -- { key = "Copy", mods = "NONE", action = act.CopyTo "Clipboard" },
        -- { key = "Paste", mods = "NONE", action = act.PasteFrom "Clipboard" },
    -- },
    --
    -- key_tables = {
    --     copy_mode = {
    --         { key = "Tab", mods = "NONE", action = act.CopyMode "MoveForwardWord" },
    --         { key = "Tab", mods = "SHIFT", action = act.CopyMode "MoveBackwardWord" },
    --         { key = "Enter", mods = "NONE", action = act.CopyMode "MoveToStartOfNextLine" },
    --         { key = "Escape", mods = "NONE", action = act.Multiple{ "ScrollToBottom", { CopyMode =  "Close" } } },
    --         { key = "Space", mods = "NONE", action = act.CopyMode{ SetSelectionMode =  "Cell" } },
    --         { key = ",", mods = "NONE", action = act.CopyMode "MoveToEndOfLineContent" },
    --   { key = ",", mods = "SHIFT", action = act.CopyMode "MoveToEndOfLineContent" },
    --         { key = ",", mods = "NONE", action = act.CopyMode "JumpReverse" },
    --         { key = "0", mods = "NONE", action = act.CopyMode "MoveToStartOfLine" },
    --         { key = ";", mods = "NONE", action = act.CopyMode "JumpAgain" },
    --         { key = "F", mods = "NONE", action = act.CopyMode{ JumpBackward = { prev_char = false } } },
    --         { key = "F", mods = "SHIFT", action = act.CopyMode{ JumpBackward = { prev_char = false } } },
    --         { key = "G", mods = "NONE", action = act.CopyMode "MoveToScrollbackBottom" },
    --         { key = "G", mods = "SHIFT", action = act.CopyMode "MoveToScrollbackBottom" },
    --         { key = "H", mods = "NONE", action = act.CopyMode "MoveToViewportTop" },
    --         { key = "H", mods = "SHIFT", action = act.CopyMode "MoveToViewportTop" },
    --         { key = "L", mods = "NONE", action = act.CopyMode "MoveToViewportBottom" },
    --         { key = "L", mods = "SHIFT", action = act.CopyMode "MoveToViewportBottom" },
    --         { key = "M", mods = "NONE", action = act.CopyMode "MoveToViewportMiddle" },
    --         { key = "M", mods = "SHIFT", action = act.CopyMode "MoveToViewportMiddle" },
    --         { key = "O", mods = "NONE", action = act.CopyMode "MoveToSelectionOtherEndHoriz" },
    --         { key = "O", mods = "SHIFT", action = act.CopyMode "MoveToSelectionOtherEndHoriz" },
    --         { key = "T", mods = "NONE", action = act.CopyMode{ JumpBackward = { prev_char = true } } },
    --         { key = "T", mods = "SHIFT", action = act.CopyMode{ JumpBackward = { prev_char = true } } },
    --         { key = "V", mods = "NONE", action = act.CopyMode{ SetSelectionMode =  "Line" } },
    --         { key = "V", mods = "SHIFT", action = act.CopyMode{ SetSelectionMode =  "Line" } },
    --         { key = "^", mods = "NONE", action = act.CopyMode "MoveToStartOfLineContent" },
    --         { key = "^", mods = "SHIFT", action = act.CopyMode "MoveToStartOfLineContent" },
    --         { key = "b", mods = "NONE", action = act.CopyMode "MoveBackwardWord" },
    --         { key = "b", mods = "ALT", action = act.CopyMode "MoveBackwardWord" },
    --         -- { key = "b", mods = "ALT", action = act.CopyMode "PageUp" },
    --         { key = "c", mods = "ALT", action = act.Multiple{ "ScrollToBottom", { CopyMode =  "Close" } } },
    --         { key = "d", mods = "ALT", action = act.CopyMode{ MoveByPage = (0.5) } },
    --         { key = "e", mods = "NONE", action = act.CopyMode "MoveForwardWordEnd" },
    --         { key = "f", mods = "NONE", action = act.CopyMode{ JumpForward = { prev_char = false } } },
    --         { key = "f", mods = "ALT", action = act.CopyMode "MoveForwardWord" },
    --         -- { key = "f", mods = "ALT", action = act.CopyMode "PageDown" },
    --         { key = "g", mods = "NONE", action = act.CopyMode "MoveToScrollbackTop" },
    --         { key = "g", mods = "ALT", action = act.Multiple{ "ScrollToBottom", { CopyMode =  "Close" } } },
    --         { key = "h", mods = "NONE", action = act.CopyMode "MoveLeft" },
    --         { key = "j", mods = "NONE", action = act.CopyMode "MoveDown" },
    --         { key = "k", mods = "NONE", action = act.CopyMode "MoveUp" },
    --         { key = "l", mods = "NONE", action = act.CopyMode "MoveRight" },
    --         { key = "m", mods = "ALT", action = act.CopyMode "MoveToStartOfLineContent" },
    --         { key = "o", mods = "NONE", action = act.CopyMode "MoveToSelectionOtherEnd" },
    --         { key = "q", mods = "NONE", action = act.Multiple{ "ScrollToBottom", { CopyMode =  "Close" } } },
    --         { key = "t", mods = "NONE", action = act.CopyMode{ JumpForward = { prev_char = true } } },
    --         { key = "u", mods = "ALT", action = act.CopyMode{ MoveByPage = (-0.5) } },
    --         { key = "v", mods = "NONE", action = act.CopyMode{ SetSelectionMode =  "Cell" } },
    --         { key = "v", mods = "ALT", action = act.CopyMode{ SetSelectionMode =  "Block" } },
    --         { key = "w", mods = "NONE", action = act.CopyMode "MoveForwardWord" },
    --         { key = "y", mods = "NONE", action = act.Multiple{ { CopyTo =  "ClipboardAndPrimarySelection" }, { Multiple = { "ScrollToBottom", { CopyMode =  "Close" } } } } },
    --         { key = "PageUp", mods = "NONE", action = act.CopyMode "PageUp" },
    --         { key = "PageDown", mods = "NONE", action = act.CopyMode "PageDown" },
    --         { key = "End", mods = "NONE", action = act.CopyMode "MoveToEndOfLineContent" },
    --         { key = "Home", mods = "NONE", action = act.CopyMode "MoveToStartOfLine" },
    --         { key = "LeftArrow", mods = "NONE", action = act.CopyMode "MoveLeft" },
    --         { key = "LeftArrow", mods = "ALT", action = act.CopyMode "MoveBackwardWord" },
    --         { key = "RightArrow", mods = "NONE", action = act.CopyMode "MoveRight" },
    --         { key = "RightArrow", mods = "ALT", action = act.CopyMode "MoveForwardWord" },
    --         { key = "UpArrow", mods = "NONE", action = act.CopyMode "MoveUp" },
    --         { key = "DownArrow", mods = "NONE", action = act.CopyMode "MoveDown" },
    --     },
    --
    --     search_mode = {
    --         { key = "Enter", mods = "NONE", action = act.CopyMode "PriorMatch" },
    --         { key = "Escape", mods = "NONE", action = act.CopyMode "Close" },
    --         { key = "n", mods = "ALT", action = act.CopyMode "NextMatch" },
    --         { key = "p", mods = "ALT", action = act.CopyMode "PriorMatch" },
    --         { key = "r", mods = "ALT", action = act.CopyMode "CycleMatchType" },
    --         { key = "u", mods = "ALT", action = act.CopyMode "ClearPattern" },
    --         { key = "PageUp", mods = "NONE", action = act.CopyMode "PriorMatchPage" },
    --         { key = "PageDown", mods = "NONE", action = act.CopyMode "NextMatchPage" },
    --         { key = "UpArrow", mods = "NONE", action = act.CopyMode "PriorMatch" },
    --         { key = "DownArrow", mods = "NONE", action = act.CopyMode "NextMatch" },
    --     },
    }
end

return M
